//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Teacher = newTeacherTable("public", "teacher", "")

type teacherTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	FirstName    postgres.ColumnString
	LastName     postgres.ColumnString
	Email        postgres.ColumnString
	Dob          postgres.ColumnDate
	DepartmentID postgres.ColumnInteger
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp
	DeletedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TeacherTable struct {
	teacherTable

	EXCLUDED teacherTable
}

// AS creates new TeacherTable with assigned alias
func (a TeacherTable) AS(alias string) *TeacherTable {
	return newTeacherTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TeacherTable with assigned schema name
func (a TeacherTable) FromSchema(schemaName string) *TeacherTable {
	return newTeacherTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TeacherTable with assigned table prefix
func (a TeacherTable) WithPrefix(prefix string) *TeacherTable {
	return newTeacherTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TeacherTable with assigned table suffix
func (a TeacherTable) WithSuffix(suffix string) *TeacherTable {
	return newTeacherTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTeacherTable(schemaName, tableName, alias string) *TeacherTable {
	return &TeacherTable{
		teacherTable: newTeacherTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newTeacherTableImpl("", "excluded", ""),
	}
}

func newTeacherTableImpl(schemaName, tableName, alias string) teacherTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		FirstNameColumn    = postgres.StringColumn("first_name")
		LastNameColumn     = postgres.StringColumn("last_name")
		EmailColumn        = postgres.StringColumn("email")
		DobColumn          = postgres.DateColumn("dob")
		DepartmentIDColumn = postgres.IntegerColumn("department_id")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		DeletedAtColumn    = postgres.TimestampColumn("deleted_at")
		allColumns         = postgres.ColumnList{IDColumn, FirstNameColumn, LastNameColumn, EmailColumn, DobColumn, DepartmentIDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns     = postgres.ColumnList{FirstNameColumn, LastNameColumn, EmailColumn, DobColumn, DepartmentIDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
	)

	return teacherTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		FirstName:    FirstNameColumn,
		LastName:     LastNameColumn,
		Email:        EmailColumn,
		Dob:          DobColumn,
		DepartmentID: DepartmentIDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		DeletedAt:    DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
