//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Assignment struct {
	ID          int32 `sql:"primary_key"`
	Title       string
	Description *string
	Type        int16
	DueDate     time.Time
	Graded      *bool
	CourseID    *int32
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	DeletedAt   *time.Time
}
